### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Shadow07777** [Chinoholo0807/blockchain-based-federate-learning#3]
Thank you.

**Comment by Chinoholo0807** [comment]
No, I don't have the paper. This is my undergraduate graduation project.

**Comment by Shadow07777** [comment]
Thanks for your reply, is it possible for you to share with me your undergraduate graduation project report, I just want to understand your idea more. Thanks for your kind understanding. this is my email : 07ramdani07@gmail.com
Thank you

**Comment by Shadow07777** [comment]
Thanks for your reply, is it possible for you to share with me your undergraduate graduation project report, I just want to understand your idea more. Thanks for your kind understanding. this is my email : [07ramdani07@gmail.com](mailto:07ramdani07@gmail.com)
Thank you

**Comment by Shadow07777** [comment]
is it possible for you to share with me your undergraduate graduation project report ?

**Comment by Chinoholo0807** [comment]
done
